(cl:defpackage robot_motion_server-msg
  (:use )
  (:export
   "<MOVEARMACTION>"
   "MOVEARMACTION"
   "<MOVEARMACTIONFEEDBACK>"
   "MOVEARMACTIONFEEDBACK"
   "<MOVEARMACTIONGOAL>"
   "MOVEARMACTIONGOAL"
   "<MOVEARMACTIONRESULT>"
   "MOVEARMACTIONRESULT"
   "<MOVEARMFEEDBACK>"
   "MOVEARMFEEDBACK"
   "<MOVEARMGOAL>"
   "MOVEARMGOAL"
   "<MOVEARMRESULT>"
   "MOVEARMRESULT"
  ))

