; Auto-generated. Do not edit!


(cl:in-package robot_motion_server-msg)


;//! \htmlinclude MoveArmResult.msg.html

(cl:defclass <MoveArmResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MoveArmResult (<MoveArmResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveArmResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveArmResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_motion_server-msg:<MoveArmResult> is deprecated: use robot_motion_server-msg:MoveArmResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveArmResult>) ostream)
  "Serializes a message object of type '<MoveArmResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveArmResult>) istream)
  "Deserializes a message object of type '<MoveArmResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveArmResult>)))
  "Returns string type for a message object of type '<MoveArmResult>"
  "robot_motion_server/MoveArmResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveArmResult)))
  "Returns string type for a message object of type 'MoveArmResult"
  "robot_motion_server/MoveArmResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveArmResult>)))
  "Returns md5sum for a message object of type '<MoveArmResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveArmResult)))
  "Returns md5sum for a message object of type 'MoveArmResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveArmResult>)))
  "Returns full string definition for message of type '<MoveArmResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#result definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveArmResult)))
  "Returns full string definition for message of type 'MoveArmResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#result definition~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveArmResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveArmResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveArmResult
))
