; Auto-generated. Do not edit!


(cl:in-package gpismap_ros-msg)


;//! \htmlinclude MoveArmGoal.msg.html

(cl:defclass <MoveArmGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type cl:string
    :initform "")
   (target_pose
    :reader target_pose
    :initarg :target_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass MoveArmGoal (<MoveArmGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveArmGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveArmGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gpismap_ros-msg:<MoveArmGoal> is deprecated: use gpismap_ros-msg:MoveArmGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <MoveArmGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gpismap_ros-msg:command-val is deprecated.  Use gpismap_ros-msg:command instead.")
  (command m))

(cl:ensure-generic-function 'target_pose-val :lambda-list '(m))
(cl:defmethod target_pose-val ((m <MoveArmGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader gpismap_ros-msg:target_pose-val is deprecated.  Use gpismap_ros-msg:target_pose instead.")
  (target_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveArmGoal>) ostream)
  "Serializes a message object of type '<MoveArmGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'command))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'command))
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveArmGoal>) istream)
  "Deserializes a message object of type '<MoveArmGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'command) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'command) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveArmGoal>)))
  "Returns string type for a message object of type '<MoveArmGoal>"
  "gpismap_ros/MoveArmGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveArmGoal)))
  "Returns string type for a message object of type 'MoveArmGoal"
  "gpismap_ros/MoveArmGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveArmGoal>)))
  "Returns md5sum for a message object of type '<MoveArmGoal>"
  "ae7bf2b71ae15ef724f90285e78b3870")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveArmGoal)))
  "Returns md5sum for a message object of type 'MoveArmGoal"
  "ae7bf2b71ae15ef724f90285e78b3870")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveArmGoal>)))
  "Returns full string definition for message of type '<MoveArmGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%~%string command #RESET: move robot to preset pose , GTWP : go to specified waypoint pose~%~%geometry_msgs/Pose target_pose~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveArmGoal)))
  "Returns full string definition for message of type 'MoveArmGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%~%string command #RESET: move robot to preset pose , GTWP : go to specified waypoint pose~%~%geometry_msgs/Pose target_pose~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveArmGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'command))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveArmGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveArmGoal
    (cl:cons ':command (command msg))
    (cl:cons ':target_pose (target_pose msg))
))
