; Auto-generated. Do not edit!


(cl:in-package gpismap_ros-msg)


;//! \htmlinclude MoveArmFeedback.msg.html

(cl:defclass <MoveArmFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MoveArmFeedback (<MoveArmFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveArmFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveArmFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name gpismap_ros-msg:<MoveArmFeedback> is deprecated: use gpismap_ros-msg:MoveArmFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveArmFeedback>) ostream)
  "Serializes a message object of type '<MoveArmFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveArmFeedback>) istream)
  "Deserializes a message object of type '<MoveArmFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveArmFeedback>)))
  "Returns string type for a message object of type '<MoveArmFeedback>"
  "gpismap_ros/MoveArmFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveArmFeedback)))
  "Returns string type for a message object of type 'MoveArmFeedback"
  "gpismap_ros/MoveArmFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveArmFeedback>)))
  "Returns md5sum for a message object of type '<MoveArmFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveArmFeedback)))
  "Returns md5sum for a message object of type 'MoveArmFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveArmFeedback>)))
  "Returns full string definition for message of type '<MoveArmFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveArmFeedback)))
  "Returns full string definition for message of type 'MoveArmFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveArmFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveArmFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveArmFeedback
))
