// Generated by gencpp from file gpismap_ros/MoveArmGoal.msg
// DO NOT EDIT!


#ifndef GPISMAP_ROS_MESSAGE_MOVEARMGOAL_H
#define GPISMAP_ROS_MESSAGE_MOVEARMGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace gpismap_ros
{
template <class ContainerAllocator>
struct MoveArmGoal_
{
  typedef MoveArmGoal_<ContainerAllocator> Type;

  MoveArmGoal_()
    : command()
    , target_pose()  {
    }
  MoveArmGoal_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , target_pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;





  typedef boost::shared_ptr< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveArmGoal_

typedef ::gpismap_ros::MoveArmGoal_<std::allocator<void> > MoveArmGoal;

typedef boost::shared_ptr< ::gpismap_ros::MoveArmGoal > MoveArmGoalPtr;
typedef boost::shared_ptr< ::gpismap_ros::MoveArmGoal const> MoveArmGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gpismap_ros::MoveArmGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gpismap_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'gpismap_ros': ['/home/abdel/catkin_ws/devel/share/gpismap_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae7bf2b71ae15ef724f90285e78b3870";
  }

  static const char* value(const ::gpismap_ros::MoveArmGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae7bf2b71ae15ef7ULL;
  static const uint64_t static_value2 = 0x24f90285e78b3870ULL;
};

template<class ContainerAllocator>
struct DataType< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gpismap_ros/MoveArmGoal";
  }

  static const char* value(const ::gpismap_ros::MoveArmGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
\n\
string command #RESET: move robot to preset pose , GTWP : go to specified waypoint pose\n\
\n\
geometry_msgs/Pose target_pose\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::gpismap_ros::MoveArmGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.target_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveArmGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gpismap_ros::MoveArmGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gpismap_ros::MoveArmGoal_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPISMAP_ROS_MESSAGE_MOVEARMGOAL_H
